// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package lifecycledb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type LocationDisablement struct {
	ID          pgtype.UUID
	LocationID  pgtype.UUID
	StartsAt    pgtype.Timestamptz
	EndsAt      pgtype.Timestamptz
	CancelledAt pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	Reason      string
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Revision    int64
}
