# Dev image with live reload via Air. Used by compose.yaml.
FROM golang:1.27.0

WORKDIR /app

RUN go install github.com/air-verse/air@v1.67.4
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

EXPOSE 8080

CMD ["sh", "-c", "goose -dir database/schema postgres \"$DATABASE_URL\" up && exec air -c .air.toml"]
