// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: location.sql

package locationdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const buildingExists = `-- name: BuildingExists :one
SELECT EXISTS(SELECT 1 FROM buildings WHERE id = $1) AS present
`

func (q *Queries) BuildingExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, buildingExists, id)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const countLocations = `-- name: CountLocations :one
SELECT count(*)
FROM locations l
WHERE ($1::TEXT = ''
        OR l.name ILIKE '%' || $1::TEXT || '%'
        OR $2::TEXT <% l.name)
    AND ($3::UUID IS NULL OR l.building_id = $3::UUID)
    AND ($4::UUID IS NULL OR EXISTS (
        SELECT 1 FROM location_categories lc
        WHERE lc.location_id = l.id AND lc.category_id = $4::UUID))
    AND (NOT $5::BOOLEAN OR l.is_supplier)
    AND ($6::TEXT = 'all'
        OR ($6::TEXT = 'active' AND l.archived_at IS NULL)
        OR ($6::TEXT = 'archived' AND l.archived_at IS NOT NULL))
`

type CountLocationsParams struct {
	Search        string
	RawSearch     string
	BuildingID    *uuid.UUID
	CategoryID    *uuid.UUID
	SuppliersOnly bool
	ArchiveFilter string
}

func (q *Queries) CountLocations(ctx context.Context, arg CountLocationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLocations,
		arg.Search,
		arg.RawSearch,
		arg.BuildingID,
		arg.CategoryID,
		arg.SuppliersOnly,
		arg.ArchiveFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLocationCategories = `-- name: DeleteLocationCategories :exec
DELETE FROM location_categories WHERE location_id = $1
`

func (q *Queries) DeleteLocationCategories(ctx context.Context, locationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocationCategories, locationID)
	return err
}

const existingCategoryIDs = `-- name: ExistingCategoryIDs :many
SELECT id FROM categories WHERE id = ANY($1::UUID[])
`

func (q *Queries) ExistingCategoryIDs(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, existingCategoryIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocation = `-- name: GetLocation :one
SELECT
    l.id,
    l.name,
    l.is_supplier,
    l.floor,
    ST_Y(l.coordinates::GEOMETRY)::DOUBLE PRECISION AS latitude,
    ST_X(l.coordinates::GEOMETRY)::DOUBLE PRECISION AS longitude,
    l.open_from,
    l.open_to,
    l.contact,
    l.details,
    l.archived_at,
    l.revision,
    l.created_at,
    l.updated_at,
    b.id AS building_id,
    b.name AS building_name,
    ST_Y(b.center::GEOMETRY)::DOUBLE PRECISION AS building_latitude,
    ST_X(b.center::GEOMETRY)::DOUBLE PRECISION AS building_longitude,
    b.radius_m AS building_radius_m
FROM locations l
JOIN buildings b ON b.id = l.building_id
WHERE l.id = $1
`

type GetLocationRow struct {
	ID                uuid.UUID
	Name              string
	IsSupplier        bool
	Floor             *string
	Latitude          float64
	Longitude         float64
	OpenFrom          pgtype.Time
	OpenTo            pgtype.Time
	Contact           *string
	Details           string
	ArchivedAt        *time.Time
	Revision          int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	BuildingID        uuid.UUID
	BuildingName      string
	BuildingLatitude  float64
	BuildingLongitude float64
	BuildingRadiusM   float32
}

func (q *Queries) GetLocation(ctx context.Context, id uuid.UUID) (GetLocationRow, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i GetLocationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSupplier,
		&i.Floor,
		&i.Latitude,
		&i.Longitude,
		&i.OpenFrom,
		&i.OpenTo,
		&i.Contact,
		&i.Details,
		&i.ArchivedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuildingID,
		&i.BuildingName,
		&i.BuildingLatitude,
		&i.BuildingLongitude,
		&i.BuildingRadiusM,
	)
	return i, err
}

const insertLocation = `-- name: InsertLocation :exec
INSERT INTO locations (
    id, name, is_supplier, building_id, floor, coordinates,
    open_from, open_to, contact, details, revision, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    ST_SetSRID(ST_MakePoint($6::DOUBLE PRECISION, $7::DOUBLE PRECISION), 4326)::geography,
    $8, $9, $10, $11, 1, $12
)
`

type InsertLocationParams struct {
	ID         uuid.UUID
	Name       string
	IsSupplier bool
	BuildingID uuid.UUID
	Floor      *string
	Longitude  float64
	Latitude   float64
	OpenFrom   pgtype.Time
	OpenTo     pgtype.Time
	Contact    *string
	Details    string
	CreatedAt  time.Time
}

func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) error {
	_, err := q.db.Exec(ctx, insertLocation,
		arg.ID,
		arg.Name,
		arg.IsSupplier,
		arg.BuildingID,
		arg.Floor,
		arg.Longitude,
		arg.Latitude,
		arg.OpenFrom,
		arg.OpenTo,
		arg.Contact,
		arg.Details,
		arg.CreatedAt,
	)
	return err
}

const insertLocationCategory = `-- name: InsertLocationCategory :exec
INSERT INTO location_categories (location_id, category_id)
VALUES ($1, $2)
`

type InsertLocationCategoryParams struct {
	LocationID uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) InsertLocationCategory(ctx context.Context, arg InsertLocationCategoryParams) error {
	_, err := q.db.Exec(ctx, insertLocationCategory, arg.LocationID, arg.CategoryID)
	return err
}

const listBuildings = `-- name: ListBuildings :many
SELECT
    id,
    name,
    ST_Y(center::GEOMETRY)::DOUBLE PRECISION AS latitude,
    ST_X(center::GEOMETRY)::DOUBLE PRECISION AS longitude,
    radius_m
FROM buildings
ORDER BY lower(name), id
`

type ListBuildingsRow struct {
	ID        uuid.UUID
	Name      string
	Latitude  float64
	Longitude float64
	RadiusM   float32
}

func (q *Queries) ListBuildings(ctx context.Context) ([]ListBuildingsRow, error) {
	rows, err := q.db.Query(ctx, listBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildingsRow
	for rows.Next() {
		var i ListBuildingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
			&i.RadiusM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name
FROM categories
ORDER BY lower(name), id
`

type ListCategoriesRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentDisablements = `-- name: ListCurrentDisablements :many
SELECT DISTINCT ON (d.location_id)
    d.location_id,
    d.id,
    d.starts_at,
    d.ends_at,
    d.reason
FROM location_disablements d
WHERE d.location_id = ANY($1::UUID[])
    AND d.cancelled_at IS NULL
    AND d.starts_at <= now()
    AND (d.ends_at IS NULL OR d.ends_at > now())
ORDER BY d.location_id, d.starts_at DESC, d.created_at DESC, d.id DESC
`

type ListCurrentDisablementsRow struct {
	LocationID uuid.UUID
	ID         uuid.UUID
	StartsAt   time.Time
	EndsAt     *time.Time
	Reason     string
}

// At most one per Location: the most recently started active interval, then
// the most recently created, then id so ties resolve the same way every time.
func (q *Queries) ListCurrentDisablements(ctx context.Context, locationIds []uuid.UUID) ([]ListCurrentDisablementsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentDisablements, locationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentDisablementsRow
	for rows.Next() {
		var i ListCurrentDisablementsRow
		if err := rows.Scan(
			&i.LocationID,
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationCategories = `-- name: ListLocationCategories :many
SELECT lc.location_id, c.id, c.name
FROM location_categories lc
JOIN categories c ON c.id = lc.category_id
WHERE lc.location_id = ANY($1::UUID[])
ORDER BY lc.location_id, lower(c.name), c.id
`

type ListLocationCategoriesRow struct {
	LocationID uuid.UUID
	ID         uuid.UUID
	Name       string
}

func (q *Queries) ListLocationCategories(ctx context.Context, locationIds []uuid.UUID) ([]ListLocationCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listLocationCategories, locationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationCategoriesRow
	for rows.Next() {
		var i ListLocationCategoriesRow
		if err := rows.Scan(&i.LocationID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT
    l.id,
    l.name,
    l.is_supplier,
    l.floor,
    ST_Y(l.coordinates::GEOMETRY)::DOUBLE PRECISION AS latitude,
    ST_X(l.coordinates::GEOMETRY)::DOUBLE PRECISION AS longitude,
    l.open_from,
    l.open_to,
    l.contact,
    l.details,
    l.archived_at,
    l.revision,
    l.created_at,
    l.updated_at,
    b.id AS building_id,
    b.name AS building_name,
    ST_Y(b.center::GEOMETRY)::DOUBLE PRECISION AS building_latitude,
    ST_X(b.center::GEOMETRY)::DOUBLE PRECISION AS building_longitude,
    b.radius_m AS building_radius_m
FROM locations l
JOIN buildings b ON b.id = l.building_id
WHERE ($1::TEXT = ''
        OR l.name ILIKE '%' || $1::TEXT || '%'
        OR $2::TEXT <% l.name)
    AND ($3::UUID IS NULL OR l.building_id = $3::UUID)
    AND ($4::UUID IS NULL OR EXISTS (
        SELECT 1 FROM location_categories lc
        WHERE lc.location_id = l.id AND lc.category_id = $4::UUID))
    AND (NOT $5::BOOLEAN OR l.is_supplier)
    AND ($6::TEXT = 'all'
        OR ($6::TEXT = 'active' AND l.archived_at IS NULL)
        OR ($6::TEXT = 'archived' AND l.archived_at IS NOT NULL))
ORDER BY
    CASE WHEN $7::TEXT = 'building' AND NOT $8::BOOLEAN THEN lower(b.name) END ASC,
    CASE WHEN $7::TEXT = 'building' AND $8::BOOLEAN THEN lower(b.name) END DESC,
    CASE WHEN NOT $8::BOOLEAN THEN lower(l.name) END ASC,
    CASE WHEN $8::BOOLEAN THEN lower(l.name) END DESC,
    CASE WHEN NOT $8::BOOLEAN THEN l.id END ASC,
    CASE WHEN $8::BOOLEAN THEN l.id END DESC
LIMIT $10 OFFSET $9
`

type ListLocationsParams struct {
	Search        string
	RawSearch     string
	BuildingID    *uuid.UUID
	CategoryID    *uuid.UUID
	SuppliersOnly bool
	ArchiveFilter string
	SortField     string
	Descending    bool
	PageOffset    int32
	PageLimit     int32
}

type ListLocationsRow struct {
	ID                uuid.UUID
	Name              string
	IsSupplier        bool
	Floor             *string
	Latitude          float64
	Longitude         float64
	OpenFrom          pgtype.Time
	OpenTo            pgtype.Time
	Contact           *string
	Details           string
	ArchivedAt        *time.Time
	Revision          int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	BuildingID        uuid.UUID
	BuildingName      string
	BuildingLatitude  float64
	BuildingLongitude float64
	BuildingRadiusM   float32
}

// Filters match CountLocations. search is a pre-escaped ILIKE pattern body;
// word similarity catches typos. Ties sort by id so pages are stable.
func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]ListLocationsRow, error) {
	rows, err := q.db.Query(ctx, listLocations,
		arg.Search,
		arg.RawSearch,
		arg.BuildingID,
		arg.CategoryID,
		arg.SuppliersOnly,
		arg.ArchiveFilter,
		arg.SortField,
		arg.Descending,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsRow
	for rows.Next() {
		var i ListLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsSupplier,
			&i.Floor,
			&i.Latitude,
			&i.Longitude,
			&i.OpenFrom,
			&i.OpenTo,
			&i.Contact,
			&i.Details,
			&i.ArchivedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BuildingID,
			&i.BuildingName,
			&i.BuildingLatitude,
			&i.BuildingLongitude,
			&i.BuildingRadiusM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLocation = `-- name: LockLocation :one
SELECT id FROM locations WHERE id = $1 FOR UPDATE
`

// Lock only the parent. Relationship reads must use a later statement after
// any concurrent holder of this lock commits.
func (q *Queries) LockLocation(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockLocation, id)
	err := row.Scan(&id)
	return id, err
}

const setLocationArchived = `-- name: SetLocationArchived :execrows
UPDATE locations SET archived_at = $1, revision = revision + 1
WHERE id = $2 AND revision = $3
`

type SetLocationArchivedParams struct {
	ArchivedAt       *time.Time
	ID               uuid.UUID
	ExpectedRevision int64
}

func (q *Queries) SetLocationArchived(ctx context.Context, arg SetLocationArchivedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLocationArchived, arg.ArchivedAt, arg.ID, arg.ExpectedRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLocation = `-- name: UpdateLocation :execrows
UPDATE locations SET
    name = $1,
    is_supplier = $2,
    building_id = $3,
    floor = $4,
    coordinates = ST_SetSRID(ST_MakePoint($5::DOUBLE PRECISION, $6::DOUBLE PRECISION), 4326)::geography,
    open_from = $7,
    open_to = $8,
    contact = $9,
    details = $10,
    revision = revision + 1
WHERE id = $11 AND revision = $12
`

type UpdateLocationParams struct {
	Name             string
	IsSupplier       bool
	BuildingID       uuid.UUID
	Floor            *string
	Longitude        float64
	Latitude         float64
	OpenFrom         pgtype.Time
	OpenTo           pgtype.Time
	Contact          *string
	Details          string
	ID               uuid.UUID
	ExpectedRevision int64
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLocation,
		arg.Name,
		arg.IsSupplier,
		arg.BuildingID,
		arg.Floor,
		arg.Longitude,
		arg.Latitude,
		arg.OpenFrom,
		arg.OpenTo,
		arg.Contact,
		arg.Details,
		arg.ID,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
