// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seed.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSeedLocationCategory = `-- name: AddSeedLocationCategory :exec
INSERT INTO location_categories (location_id, category_id)
VALUES ($1, $2)
ON CONFLICT (location_id, category_id) DO NOTHING
`

type AddSeedLocationCategoryParams struct {
	LocationID pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) AddSeedLocationCategory(ctx context.Context, arg AddSeedLocationCategoryParams) error {
	_, err := q.db.Exec(ctx, addSeedLocationCategory, arg.LocationID, arg.CategoryID)
	return err
}

const deleteAllSeedLocationCategories = `-- name: DeleteAllSeedLocationCategories :execrows
DELETE FROM location_categories
WHERE location_id = $1
`

func (q *Queries) DeleteAllSeedLocationCategories(ctx context.Context, locationID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllSeedLocationCategories, locationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSeedLocationCategory = `-- name: DeleteSeedLocationCategory :exec
DELETE FROM location_categories
WHERE location_id = $1 AND category_id = $2
`

type DeleteSeedLocationCategoryParams struct {
	LocationID pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) DeleteSeedLocationCategory(ctx context.Context, arg DeleteSeedLocationCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteSeedLocationCategory, arg.LocationID, arg.CategoryID)
	return err
}

const getSeedBuilding = `-- name: GetSeedBuilding :one
SELECT id
FROM buildings
WHERE id = $1 OR name = $2
ORDER BY (id = $1) DESC
LIMIT 1
`

type GetSeedBuildingParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) GetSeedBuilding(ctx context.Context, arg GetSeedBuildingParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSeedBuilding, arg.ID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getSeedCategory = `-- name: GetSeedCategory :one
SELECT id
FROM categories
WHERE id = $1 OR name = $2
ORDER BY (id = $1) DESC
LIMIT 1
`

type GetSeedCategoryParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) GetSeedCategory(ctx context.Context, arg GetSeedCategoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSeedCategory, arg.ID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listSeedLocationCategoryIDs = `-- name: ListSeedLocationCategoryIDs :many
SELECT category_id
FROM location_categories
WHERE location_id = $1
ORDER BY category_id
`

func (q *Queries) ListSeedLocationCategoryIDs(ctx context.Context, locationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSeedLocationCategoryIDs, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var category_id pgtype.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedLocationExists = `-- name: SeedLocationExists :one
SELECT EXISTS (
    SELECT 1
    FROM locations
    WHERE id = $1
)
`

func (q *Queries) SeedLocationExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, seedLocationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertSeedBuilding = `-- name: UpsertSeedBuilding :execrows
INSERT INTO buildings (id, name, center, radius_m)
VALUES (
    $1,
    $2,
    ST_SetSRID(
        ST_MakePoint(
            $3::DOUBLE PRECISION,
            $4::DOUBLE PRECISION
        ),
        4326
    )::GEOGRAPHY,
    $5
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    center = EXCLUDED.center,
    radius_m = EXCLUDED.radius_m
WHERE buildings.name IS DISTINCT FROM EXCLUDED.name
   OR NOT ST_Equals(buildings.center::GEOMETRY, EXCLUDED.center::GEOMETRY)
   OR buildings.radius_m IS DISTINCT FROM EXCLUDED.radius_m
`

type UpsertSeedBuildingParams struct {
	ID        pgtype.UUID
	Name      string
	Longitude float64
	Latitude  float64
	RadiusM   float32
}

func (q *Queries) UpsertSeedBuilding(ctx context.Context, arg UpsertSeedBuildingParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertSeedBuilding,
		arg.ID,
		arg.Name,
		arg.Longitude,
		arg.Latitude,
		arg.RadiusM,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSeedCategory = `-- name: UpsertSeedCategory :execrows
INSERT INTO categories (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name
WHERE categories.name IS DISTINCT FROM EXCLUDED.name
`

type UpsertSeedCategoryParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpsertSeedCategory(ctx context.Context, arg UpsertSeedCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertSeedCategory, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSeedLocation = `-- name: UpsertSeedLocation :execrows
INSERT INTO locations (
    id,
    name,
    is_supplier,
    building_id,
    floor,
    coordinates,
    open_from,
    open_to,
    contact,
    details
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    ST_SetSRID(
        ST_MakePoint(
            $6::DOUBLE PRECISION,
            $7::DOUBLE PRECISION
        ),
        4326
    )::GEOGRAPHY,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    is_supplier = EXCLUDED.is_supplier,
    building_id = EXCLUDED.building_id,
    floor = EXCLUDED.floor,
    coordinates = EXCLUDED.coordinates,
    open_from = EXCLUDED.open_from,
    open_to = EXCLUDED.open_to,
    contact = EXCLUDED.contact,
    details = EXCLUDED.details,
    revision = locations.revision + 1
WHERE locations.name IS DISTINCT FROM EXCLUDED.name
   OR locations.is_supplier IS DISTINCT FROM EXCLUDED.is_supplier
   OR locations.building_id IS DISTINCT FROM EXCLUDED.building_id
   OR locations.floor IS DISTINCT FROM EXCLUDED.floor
   OR NOT ST_Equals(locations.coordinates::GEOMETRY, EXCLUDED.coordinates::GEOMETRY)
   OR locations.open_from IS DISTINCT FROM EXCLUDED.open_from
   OR locations.open_to IS DISTINCT FROM EXCLUDED.open_to
   OR locations.contact IS DISTINCT FROM EXCLUDED.contact
   OR locations.details IS DISTINCT FROM EXCLUDED.details
`

type UpsertSeedLocationParams struct {
	ID         pgtype.UUID
	Name       string
	IsSupplier bool
	BuildingID pgtype.UUID
	Floor      pgtype.Text
	Longitude  float64
	Latitude   float64
	OpenFrom   pgtype.Time
	OpenTo     pgtype.Time
	Contact    pgtype.Text
	Details    string
}

func (q *Queries) UpsertSeedLocation(ctx context.Context, arg UpsertSeedLocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertSeedLocation,
		arg.ID,
		arg.Name,
		arg.IsSupplier,
		arg.BuildingID,
		arg.Floor,
		arg.Longitude,
		arg.Latitude,
		arg.OpenFrom,
		arg.OpenTo,
		arg.Contact,
		arg.Details,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
