// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package idempotencydb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredIdempotency = `-- name: DeleteExpiredIdempotency :exec
DELETE FROM supplier_idempotency
WHERE caller_id=$1 AND method=$2 AND key=$3::uuid
    AND expires_at<=$4::timestamptz
`

type DeleteExpiredIdempotencyParams struct {
	CallerID string
	Method   string
	Key      uuid.UUID
	NowAt    time.Time
}

func (q *Queries) DeleteExpiredIdempotency(ctx context.Context, arg DeleteExpiredIdempotencyParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotency,
		arg.CallerID,
		arg.Method,
		arg.Key,
		arg.NowAt,
	)
	return err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT caller_id, method, key, request_hash, resource_id, expires_at FROM supplier_idempotency WHERE caller_id=$1 AND method=$2 AND key=$3
`

type GetIdempotencyParams struct {
	CallerID string
	Method   string
	Key      uuid.UUID
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (SupplierIdempotency, error) {
	row := q.db.QueryRow(ctx, getIdempotency, arg.CallerID, arg.Method, arg.Key)
	var i SupplierIdempotency
	err := row.Scan(
		&i.CallerID,
		&i.Method,
		&i.Key,
		&i.RequestHash,
		&i.ResourceID,
		&i.ExpiresAt,
	)
	return i, err
}

const insertIdempotency = `-- name: InsertIdempotency :exec
INSERT INTO supplier_idempotency (caller_id,method,key,request_hash,resource_id,expires_at) VALUES ($1,$2,$3,$4,$5,$6)
`

type InsertIdempotencyParams struct {
	CallerID    string
	Method      string
	Key         uuid.UUID
	RequestHash string
	ResourceID  uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotency,
		arg.CallerID,
		arg.Method,
		arg.Key,
		arg.RequestHash,
		arg.ResourceID,
		arg.ExpiresAt,
	)
	return err
}

const lockIdempotency = `-- name: LockIdempotency :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,0))
`

func (q *Queries) LockIdempotency(ctx context.Context, scope string) error {
	_, err := q.db.Exec(ctx, lockIdempotency, scope)
	return err
}
