// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package idempotencydb

import (
	"time"

	"github.com/google/uuid"
)

type SupplierIdempotency struct {
	CallerID    string
	Method      string
	Key         uuid.UUID
	RequestHash string
	ResourceID  uuid.UUID
	ExpiresAt   time.Time
}
