// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seed.sql

package seeddb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addLocationCategory = `-- name: AddLocationCategory :exec
INSERT INTO location_categories (location_id, category_id)
VALUES ($1, $2)
ON CONFLICT (location_id, category_id) DO NOTHING
`

type AddLocationCategoryParams struct {
	LocationID pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) AddLocationCategory(ctx context.Context, arg AddLocationCategoryParams) error {
	_, err := q.db.Exec(ctx, addLocationCategory, arg.LocationID, arg.CategoryID)
	return err
}

const deleteAllLocationCategories = `-- name: DeleteAllLocationCategories :execrows
DELETE FROM location_categories
WHERE location_id = $1
`

func (q *Queries) DeleteAllLocationCategories(ctx context.Context, locationID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllLocationCategories, locationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLocationCategory = `-- name: DeleteLocationCategory :exec
DELETE FROM location_categories
WHERE location_id = $1 AND category_id = $2
`

type DeleteLocationCategoryParams struct {
	LocationID pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) DeleteLocationCategory(ctx context.Context, arg DeleteLocationCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteLocationCategory, arg.LocationID, arg.CategoryID)
	return err
}

const getBuilding = `-- name: GetBuilding :one
SELECT id
FROM buildings
WHERE id = $1 OR name = $2
ORDER BY (id = $1) DESC
LIMIT 1
`

type GetBuildingParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) GetBuilding(ctx context.Context, arg GetBuildingParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getBuilding, arg.ID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getCategory = `-- name: GetCategory :one
SELECT id
FROM categories
WHERE id = $1 OR name = $2
ORDER BY (id = $1) DESC
LIMIT 1
`

type GetCategoryParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listLocationCategoryIDs = `-- name: ListLocationCategoryIDs :many
SELECT category_id
FROM location_categories
WHERE location_id = $1
ORDER BY category_id
`

func (q *Queries) ListLocationCategoryIDs(ctx context.Context, locationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listLocationCategoryIDs, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var category_id pgtype.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationExists = `-- name: LocationExists :one
SELECT EXISTS (
    SELECT 1
    FROM locations
    WHERE id = $1
)
`

func (q *Queries) LocationExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, locationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertBuilding = `-- name: UpsertBuilding :execrows
INSERT INTO buildings (id, name, center, radius_m)
VALUES (
    $1,
    $2,
    ST_SetSRID(
        ST_MakePoint(
            $3::DOUBLE PRECISION,
            $4::DOUBLE PRECISION
        ),
        4326
    )::GEOGRAPHY,
    $5
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    center = EXCLUDED.center,
    radius_m = EXCLUDED.radius_m
WHERE buildings.name IS DISTINCT FROM EXCLUDED.name
   OR NOT ST_Equals(buildings.center::GEOMETRY, EXCLUDED.center::GEOMETRY)
   OR buildings.radius_m IS DISTINCT FROM EXCLUDED.radius_m
`

type UpsertBuildingParams struct {
	ID        pgtype.UUID
	Name      string
	Longitude float64
	Latitude  float64
	RadiusM   float32
}

func (q *Queries) UpsertBuilding(ctx context.Context, arg UpsertBuildingParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertBuilding,
		arg.ID,
		arg.Name,
		arg.Longitude,
		arg.Latitude,
		arg.RadiusM,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCategory = `-- name: UpsertCategory :execrows
INSERT INTO categories (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name
WHERE categories.name IS DISTINCT FROM EXCLUDED.name
`

type UpsertCategoryParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertCategory, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertLocation = `-- name: UpsertLocation :execrows
INSERT INTO locations (
    id,
    name,
    is_supplier,
    building_id,
    floor,
    coordinates,
    open_from,
    open_to,
    contact,
    details
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    ST_SetSRID(
        ST_MakePoint(
            $6::DOUBLE PRECISION,
            $7::DOUBLE PRECISION
        ),
        4326
    )::GEOGRAPHY,
    $8,
    $9,
    $10,
    COALESCE($11::TEXT, '')
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    is_supplier = EXCLUDED.is_supplier,
    building_id = EXCLUDED.building_id,
    floor = COALESCE($5, locations.floor),
    coordinates = EXCLUDED.coordinates,
    open_from = COALESCE($8, locations.open_from),
    open_to = COALESCE($9, locations.open_to),
    contact = COALESCE(EXCLUDED.contact, locations.contact),
    details = COALESCE($11::TEXT, locations.details),
    revision = locations.revision + 1
WHERE locations.name IS DISTINCT FROM EXCLUDED.name
   OR locations.is_supplier IS DISTINCT FROM EXCLUDED.is_supplier
   OR locations.building_id IS DISTINCT FROM EXCLUDED.building_id
   OR locations.floor IS DISTINCT FROM COALESCE($5, locations.floor)
   OR NOT ST_Equals(locations.coordinates::GEOMETRY, EXCLUDED.coordinates::GEOMETRY)
   OR locations.open_from IS DISTINCT FROM COALESCE($8, locations.open_from)
   OR locations.open_to IS DISTINCT FROM COALESCE($9, locations.open_to)
   OR locations.contact IS DISTINCT FROM COALESCE(EXCLUDED.contact, locations.contact)
   OR locations.details IS DISTINCT FROM COALESCE($11::TEXT, locations.details)
`

type UpsertLocationParams struct {
	ID         pgtype.UUID
	Name       string
	IsSupplier bool
	BuildingID pgtype.UUID
	Floor      pgtype.Text
	Longitude  float64
	Latitude   float64
	OpenFrom   pgtype.Time
	OpenTo     pgtype.Time
	Contact    pgtype.Text
	Details    pgtype.Text
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertLocation,
		arg.ID,
		arg.Name,
		arg.IsSupplier,
		arg.BuildingID,
		arg.Floor,
		arg.Longitude,
		arg.Latitude,
		arg.OpenFrom,
		arg.OpenTo,
		arg.Contact,
		arg.Details,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
