// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow.sql

package workflowdb

import (
	"context"

	postgis "github.com/cridenour/go-postgis"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkflowDisablements = `-- name: CountWorkflowDisablements :one
SELECT count(*) FROM location_disablements WHERE location_id=$1 AND (
    $2::text='' OR $2::text=CASE
    WHEN cancelled_at IS NOT NULL THEN 'cancelled'
    WHEN ended_at IS NOT NULL OR ends_at <= $3::timestamptz THEN 'ended'
    WHEN starts_at > $3::timestamptz THEN 'scheduled' ELSE 'active' END
)
`

type CountWorkflowDisablementsParams struct {
	LocationID pgtype.UUID
	State      string
	NowAt      pgtype.Timestamptz
}

func (q *Queries) CountWorkflowDisablements(ctx context.Context, arg CountWorkflowDisablementsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowDisablements, arg.LocationID, arg.State, arg.NowAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkflowRequests = `-- name: CountWorkflowRequests :one
SELECT count(*) FROM location_addition_requests
WHERE ($1::boolean OR submitted_by=$2::text OR status='approved')
    AND ($3::text='' OR status=$3::text)
`

type CountWorkflowRequestsParams struct {
	IsAdmin      bool
	CallerID     string
	StatusFilter string
}

func (q *Queries) CountWorkflowRequests(ctx context.Context, arg CountWorkflowRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowRequests, arg.IsAdmin, arg.CallerID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const currentWorkflowDisablement = `-- name: CurrentWorkflowDisablement :one
SELECT id, location_id, starts_at, ends_at, cancelled_at, reason, created_by, created_at, ended_at, updated_at, revision FROM location_disablements WHERE location_id=$1 AND cancelled_at IS NULL AND ended_at IS NULL
AND starts_at<=$2::timestamptz AND (ends_at IS NULL OR ends_at>$2::timestamptz)
ORDER BY starts_at DESC,id LIMIT 1
`

type CurrentWorkflowDisablementParams struct {
	LocationID pgtype.UUID
	NowAt      pgtype.Timestamptz
}

func (q *Queries) CurrentWorkflowDisablement(ctx context.Context, arg CurrentWorkflowDisablementParams) (LocationDisablement, error) {
	row := q.db.QueryRow(ctx, currentWorkflowDisablement, arg.LocationID, arg.NowAt)
	var i LocationDisablement
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.StartsAt,
		&i.EndsAt,
		&i.CancelledAt,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const deleteExpiredWorkflowIdempotency = `-- name: DeleteExpiredWorkflowIdempotency :exec
DELETE FROM supplier_idempotency WHERE expires_at<=$1::timestamptz
`

func (q *Queries) DeleteExpiredWorkflowIdempotency(ctx context.Context, nowAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredWorkflowIdempotency, nowAt)
	return err
}

const deleteWorkflowRequestCategories = `-- name: DeleteWorkflowRequestCategories :exec
DELETE FROM location_addition_request_categories WHERE request_id=$1
`

func (q *Queries) DeleteWorkflowRequestCategories(ctx context.Context, requestID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflowRequestCategories, requestID)
	return err
}

const getWorkflowIdempotency = `-- name: GetWorkflowIdempotency :one
SELECT caller_id, method, key, request_hash, resource_id, expires_at FROM supplier_idempotency WHERE caller_id=$1 AND method=$2 AND key=$3
`

type GetWorkflowIdempotencyParams struct {
	CallerID string
	Method   string
	Key      pgtype.UUID
}

func (q *Queries) GetWorkflowIdempotency(ctx context.Context, arg GetWorkflowIdempotencyParams) (SupplierIdempotency, error) {
	row := q.db.QueryRow(ctx, getWorkflowIdempotency, arg.CallerID, arg.Method, arg.Key)
	var i SupplierIdempotency
	err := row.Scan(
		&i.CallerID,
		&i.Method,
		&i.Key,
		&i.RequestHash,
		&i.ResourceID,
		&i.ExpiresAt,
	)
	return i, err
}

const insertWorkflowDisablement = `-- name: InsertWorkflowDisablement :exec
INSERT INTO location_disablements (id,location_id,starts_at,ends_at,reason,created_by,revision,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertWorkflowDisablementParams struct {
	ID         pgtype.UUID
	LocationID pgtype.UUID
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	Reason     string
	CreatedBy  string
	Revision   int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertWorkflowDisablement(ctx context.Context, arg InsertWorkflowDisablementParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowDisablement,
		arg.ID,
		arg.LocationID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Reason,
		arg.CreatedBy,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertWorkflowIdempotency = `-- name: InsertWorkflowIdempotency :exec
INSERT INTO supplier_idempotency (caller_id,method,key,request_hash,resource_id,expires_at) VALUES ($1,$2,$3,$4,$5,$6)
`

type InsertWorkflowIdempotencyParams struct {
	CallerID    string
	Method      string
	Key         pgtype.UUID
	RequestHash string
	ResourceID  pgtype.UUID
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) InsertWorkflowIdempotency(ctx context.Context, arg InsertWorkflowIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowIdempotency,
		arg.CallerID,
		arg.Method,
		arg.Key,
		arg.RequestHash,
		arg.ResourceID,
		arg.ExpiresAt,
	)
	return err
}

const insertWorkflowLocation = `-- name: InsertWorkflowLocation :exec
INSERT INTO locations (id,name,is_supplier,building_id,floor,coordinates,open_from,open_to,contact,details,revision,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,ST_SetSRID(ST_MakePoint($11::float8,$12::float8),4326)::geography,$6,$7,$8,$9,1,$10,$10)
`

type InsertWorkflowLocationParams struct {
	ID         pgtype.UUID
	Name       string
	IsSupplier bool
	BuildingID pgtype.UUID
	Floor      pgtype.Text
	OpenFrom   pgtype.Time
	OpenTo     pgtype.Time
	Contact    pgtype.Text
	Details    string
	CreatedAt  pgtype.Timestamptz
	Longitude  float64
	Latitude   float64
}

func (q *Queries) InsertWorkflowLocation(ctx context.Context, arg InsertWorkflowLocationParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowLocation,
		arg.ID,
		arg.Name,
		arg.IsSupplier,
		arg.BuildingID,
		arg.Floor,
		arg.OpenFrom,
		arg.OpenTo,
		arg.Contact,
		arg.Details,
		arg.CreatedAt,
		arg.Longitude,
		arg.Latitude,
	)
	return err
}

const insertWorkflowLocationCategory = `-- name: InsertWorkflowLocationCategory :exec
INSERT INTO location_categories (location_id,category_id) VALUES ($1,$2)
`

type InsertWorkflowLocationCategoryParams struct {
	LocationID pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) InsertWorkflowLocationCategory(ctx context.Context, arg InsertWorkflowLocationCategoryParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowLocationCategory, arg.LocationID, arg.CategoryID)
	return err
}

const insertWorkflowRequest = `-- name: InsertWorkflowRequest :exec
INSERT INTO location_addition_requests (id,submitted_by,name,is_supplier,building_id,floor,coordinates,open_from,open_to,contact,details,status,revision,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,ST_SetSRID(ST_MakePoint($12::float8,$13::float8),4326)::geography,$7,$8,$9,$10,'pending',1,$11,$11)
`

type InsertWorkflowRequestParams struct {
	ID          pgtype.UUID
	SubmittedBy string
	Name        string
	IsSupplier  bool
	BuildingID  pgtype.UUID
	Floor       pgtype.Text
	OpenFrom    pgtype.Time
	OpenTo      pgtype.Time
	Contact     pgtype.Text
	Details     string
	CreatedAt   pgtype.Timestamptz
	Longitude   float64
	Latitude    float64
}

func (q *Queries) InsertWorkflowRequest(ctx context.Context, arg InsertWorkflowRequestParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowRequest,
		arg.ID,
		arg.SubmittedBy,
		arg.Name,
		arg.IsSupplier,
		arg.BuildingID,
		arg.Floor,
		arg.OpenFrom,
		arg.OpenTo,
		arg.Contact,
		arg.Details,
		arg.CreatedAt,
		arg.Longitude,
		arg.Latitude,
	)
	return err
}

const insertWorkflowRequestCategory = `-- name: InsertWorkflowRequestCategory :exec
INSERT INTO location_addition_request_categories (request_id,category_id) VALUES ($1,$2)
`

type InsertWorkflowRequestCategoryParams struct {
	RequestID  pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) InsertWorkflowRequestCategory(ctx context.Context, arg InsertWorkflowRequestCategoryParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowRequestCategory, arg.RequestID, arg.CategoryID)
	return err
}

const listWorkflowDisablements = `-- name: ListWorkflowDisablements :many
SELECT id, location_id, starts_at, ends_at, cancelled_at, reason, created_by, created_at, ended_at, updated_at, revision FROM location_disablements WHERE location_id=$1 AND (
    $2::text='' OR $2::text=CASE
    WHEN cancelled_at IS NOT NULL THEN 'cancelled'
    WHEN ended_at IS NOT NULL OR ends_at <= $3::timestamptz THEN 'ended'
    WHEN starts_at > $3::timestamptz THEN 'scheduled' ELSE 'active' END
) ORDER BY starts_at DESC,id LIMIT $5 OFFSET $4::bigint
`

type ListWorkflowDisablementsParams struct {
	LocationID pgtype.UUID
	State      string
	NowAt      pgtype.Timestamptz
	PageOffset int64
	PageSize   int32
}

func (q *Queries) ListWorkflowDisablements(ctx context.Context, arg ListWorkflowDisablementsParams) ([]LocationDisablement, error) {
	rows, err := q.db.Query(ctx, listWorkflowDisablements,
		arg.LocationID,
		arg.State,
		arg.NowAt,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocationDisablement
	for rows.Next() {
		var i LocationDisablement
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.StartsAt,
			&i.EndsAt,
			&i.CancelledAt,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.EndedAt,
			&i.UpdatedAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRequests = `-- name: ListWorkflowRequests :many
SELECT r.id, r.submitted_by, r.name, r.is_supplier, r.category_id, r.building_id, r.coordinates, r.open_from, r.open_to, r.contact, r.details, r.status, r.reviewed_by, r.reviewed_at, r.review_note, r.resulting_location_id, r.created_at, r.updated_at, r.floor, r.revision, COALESCE(ST_Y(r.coordinates::geometry),0)::float8 AS latitude,
    COALESCE(ST_X(r.coordinates::geometry),0)::float8 AS longitude,
    ARRAY(SELECT category_id FROM location_addition_request_categories WHERE request_id=r.id ORDER BY category_id)::uuid[] AS category_ids
FROM location_addition_requests r
WHERE ($1::boolean OR submitted_by=$2::text OR status='approved')
    AND ($3::text='' OR status=$3::text)
ORDER BY created_at DESC,id LIMIT $5 OFFSET $4::bigint
`

type ListWorkflowRequestsParams struct {
	IsAdmin      bool
	CallerID     string
	StatusFilter string
	PageOffset   int64
	PageSize     int32
}

type ListWorkflowRequestsRow struct {
	ID                  pgtype.UUID
	SubmittedBy         string
	Name                string
	IsSupplier          bool
	CategoryID          pgtype.UUID
	BuildingID          pgtype.UUID
	Coordinates         *postgis.PointS
	OpenFrom            pgtype.Time
	OpenTo              pgtype.Time
	Contact             pgtype.Text
	Details             string
	Status              string
	ReviewedBy          pgtype.Text
	ReviewedAt          pgtype.Timestamptz
	ReviewNote          pgtype.Text
	ResultingLocationID pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Floor               pgtype.Text
	Revision            int64
	Latitude            float64
	Longitude           float64
	CategoryIds         []pgtype.UUID
}

func (q *Queries) ListWorkflowRequests(ctx context.Context, arg ListWorkflowRequestsParams) ([]ListWorkflowRequestsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowRequests,
		arg.IsAdmin,
		arg.CallerID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowRequestsRow
	for rows.Next() {
		var i ListWorkflowRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.Name,
			&i.IsSupplier,
			&i.CategoryID,
			&i.BuildingID,
			&i.Coordinates,
			&i.OpenFrom,
			&i.OpenTo,
			&i.Contact,
			&i.Details,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.ResultingLocationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Floor,
			&i.Revision,
			&i.Latitude,
			&i.Longitude,
			&i.CategoryIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkflowDisablement = `-- name: LockWorkflowDisablement :one
SELECT id, location_id, starts_at, ends_at, cancelled_at, reason, created_by, created_at, ended_at, updated_at, revision FROM location_disablements WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockWorkflowDisablement(ctx context.Context, id pgtype.UUID) (LocationDisablement, error) {
	row := q.db.QueryRow(ctx, lockWorkflowDisablement, id)
	var i LocationDisablement
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.StartsAt,
		&i.EndsAt,
		&i.CancelledAt,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const lockWorkflowIdempotency = `-- name: LockWorkflowIdempotency :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,0))
`

func (q *Queries) LockWorkflowIdempotency(ctx context.Context, scope string) error {
	_, err := q.db.Exec(ctx, lockWorkflowIdempotency, scope)
	return err
}

const lockWorkflowLocation = `-- name: LockWorkflowLocation :one
SELECT l.id, l.name, l.is_supplier, l.building_id, l.floor, l.coordinates, l.open_from, l.open_to, l.contact, l.details, l.archived_at, l.revision, l.created_at, l.updated_at, ST_Y(l.coordinates::geometry)::float8 AS latitude,
    ST_X(l.coordinates::geometry)::float8 AS longitude,
    b.name AS building_name, ST_Y(b.center::geometry)::float8 AS building_latitude,
    ST_X(b.center::geometry)::float8 AS building_longitude, b.radius_m,
    b.created_at AS building_created_at, b.updated_at AS building_updated_at,
    ARRAY(SELECT category_id FROM location_categories WHERE location_id=l.id ORDER BY category_id)::uuid[] AS category_ids
FROM locations l JOIN buildings b ON b.id=l.building_id WHERE l.id=$1 FOR UPDATE OF l
`

type LockWorkflowLocationRow struct {
	ID                pgtype.UUID
	Name              string
	IsSupplier        bool
	BuildingID        pgtype.UUID
	Floor             pgtype.Text
	Coordinates       postgis.PointS
	OpenFrom          pgtype.Time
	OpenTo            pgtype.Time
	Contact           pgtype.Text
	Details           string
	ArchivedAt        pgtype.Timestamptz
	Revision          int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Latitude          float64
	Longitude         float64
	BuildingName      string
	BuildingLatitude  float64
	BuildingLongitude float64
	RadiusM           float32
	BuildingCreatedAt pgtype.Timestamptz
	BuildingUpdatedAt pgtype.Timestamptz
	CategoryIds       []pgtype.UUID
}

func (q *Queries) LockWorkflowLocation(ctx context.Context, id pgtype.UUID) (LockWorkflowLocationRow, error) {
	row := q.db.QueryRow(ctx, lockWorkflowLocation, id)
	var i LockWorkflowLocationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSupplier,
		&i.BuildingID,
		&i.Floor,
		&i.Coordinates,
		&i.OpenFrom,
		&i.OpenTo,
		&i.Contact,
		&i.Details,
		&i.ArchivedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.BuildingName,
		&i.BuildingLatitude,
		&i.BuildingLongitude,
		&i.RadiusM,
		&i.BuildingCreatedAt,
		&i.BuildingUpdatedAt,
		&i.CategoryIds,
	)
	return i, err
}

const lockWorkflowRequest = `-- name: LockWorkflowRequest :one
SELECT r.id, r.submitted_by, r.name, r.is_supplier, r.category_id, r.building_id, r.coordinates, r.open_from, r.open_to, r.contact, r.details, r.status, r.reviewed_by, r.reviewed_at, r.review_note, r.resulting_location_id, r.created_at, r.updated_at, r.floor, r.revision, COALESCE(ST_Y(r.coordinates::geometry),0)::float8 AS latitude,
    COALESCE(ST_X(r.coordinates::geometry),0)::float8 AS longitude,
    ARRAY[]::uuid[] AS category_ids
FROM location_addition_requests r WHERE r.id=$1 FOR UPDATE
`

type LockWorkflowRequestRow struct {
	ID                  pgtype.UUID
	SubmittedBy         string
	Name                string
	IsSupplier          bool
	CategoryID          pgtype.UUID
	BuildingID          pgtype.UUID
	Coordinates         *postgis.PointS
	OpenFrom            pgtype.Time
	OpenTo              pgtype.Time
	Contact             pgtype.Text
	Details             string
	Status              string
	ReviewedBy          pgtype.Text
	ReviewedAt          pgtype.Timestamptz
	ReviewNote          pgtype.Text
	ResultingLocationID pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Floor               pgtype.Text
	Revision            int64
	Latitude            float64
	Longitude           float64
	CategoryIds         []pgtype.UUID
}

func (q *Queries) LockWorkflowRequest(ctx context.Context, id pgtype.UUID) (LockWorkflowRequestRow, error) {
	row := q.db.QueryRow(ctx, lockWorkflowRequest, id)
	var i LockWorkflowRequestRow
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.Name,
		&i.IsSupplier,
		&i.CategoryID,
		&i.BuildingID,
		&i.Coordinates,
		&i.OpenFrom,
		&i.OpenTo,
		&i.Contact,
		&i.Details,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.ResultingLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Floor,
		&i.Revision,
		&i.Latitude,
		&i.Longitude,
		&i.CategoryIds,
	)
	return i, err
}

const updateWorkflowDisablement = `-- name: UpdateWorkflowDisablement :execrows
UPDATE location_disablements SET starts_at=$2, ends_at=$3, ended_at=$4, cancelled_at=$5, reason=$6,
    revision=$7, updated_at=$8 WHERE id=$1 AND revision=$9
`

type UpdateWorkflowDisablementParams struct {
	ID               pgtype.UUID
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	EndedAt          pgtype.Timestamptz
	CancelledAt      pgtype.Timestamptz
	Reason           string
	Revision         int64
	UpdatedAt        pgtype.Timestamptz
	ExpectedRevision int64
}

func (q *Queries) UpdateWorkflowDisablement(ctx context.Context, arg UpdateWorkflowDisablementParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWorkflowDisablement,
		arg.ID,
		arg.StartsAt,
		arg.EndsAt,
		arg.EndedAt,
		arg.CancelledAt,
		arg.Reason,
		arg.Revision,
		arg.UpdatedAt,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWorkflowRequest = `-- name: UpdateWorkflowRequest :execrows
UPDATE location_addition_requests SET name=$2,is_supplier=$3,building_id=$4,floor=$5,
    coordinates=CASE WHEN $17::boolean THEN NULL ELSE ST_SetSRID(ST_MakePoint($18::float8,$19::float8),4326)::geography END,
    open_from=$6,open_to=$7,contact=$8,details=$9,status=$10,reviewed_by=$11,reviewed_at=$12,review_note=$13,
    resulting_location_id=$14,revision=$15,updated_at=$16
WHERE id=$1 AND status='pending' AND revision=$20
`

type UpdateWorkflowRequestParams struct {
	ID                  pgtype.UUID
	Name                string
	IsSupplier          bool
	BuildingID          pgtype.UUID
	Floor               pgtype.Text
	OpenFrom            pgtype.Time
	OpenTo              pgtype.Time
	Contact             pgtype.Text
	Details             string
	Status              string
	ReviewedBy          pgtype.Text
	ReviewedAt          pgtype.Timestamptz
	ReviewNote          pgtype.Text
	ResultingLocationID pgtype.UUID
	Revision            int64
	UpdatedAt           pgtype.Timestamptz
	CoordinatesMissing  bool
	Longitude           float64
	Latitude            float64
	ExpectedRevision    int64
}

func (q *Queries) UpdateWorkflowRequest(ctx context.Context, arg UpdateWorkflowRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWorkflowRequest,
		arg.ID,
		arg.Name,
		arg.IsSupplier,
		arg.BuildingID,
		arg.Floor,
		arg.OpenFrom,
		arg.OpenTo,
		arg.Contact,
		arg.Details,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.ReviewNote,
		arg.ResultingLocationID,
		arg.Revision,
		arg.UpdatedAt,
		arg.CoordinatesMissing,
		arg.Longitude,
		arg.Latitude,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const workflowBuildingExists = `-- name: WorkflowBuildingExists :one
SELECT EXISTS(SELECT 1 FROM buildings WHERE id=$1)
`

func (q *Queries) WorkflowBuildingExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workflowBuildingExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const workflowCategoryExists = `-- name: WorkflowCategoryExists :one
SELECT EXISTS(SELECT 1 FROM categories WHERE id=$1)
`

func (q *Queries) WorkflowCategoryExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workflowCategoryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const workflowDisablementOverlap = `-- name: WorkflowDisablementOverlap :one
SELECT EXISTS(SELECT 1 FROM location_disablements
WHERE location_id=$1 AND id<>$2 AND cancelled_at IS NULL
    AND tstzrange(starts_at, LEAST(ends_at,ended_at), '[)') && tstzrange($3::timestamptz,$4::timestamptz,'[)'))
`

type WorkflowDisablementOverlapParams struct {
	LocationID pgtype.UUID
	ID         pgtype.UUID
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
}

func (q *Queries) WorkflowDisablementOverlap(ctx context.Context, arg WorkflowDisablementOverlapParams) (bool, error) {
	row := q.db.QueryRow(ctx, workflowDisablementOverlap,
		arg.LocationID,
		arg.ID,
		arg.StartsAt,
		arg.EndsAt,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const workflowLocationCategories = `-- name: WorkflowLocationCategories :many
SELECT c.id, c.name, c.created_at FROM categories c JOIN location_categories lc ON lc.category_id=c.id
WHERE lc.location_id=$1 ORDER BY c.id
`

func (q *Queries) WorkflowLocationCategories(ctx context.Context, locationID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, workflowLocationCategories, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowRequestCategoryIDs = `-- name: WorkflowRequestCategoryIDs :many
SELECT category_id FROM location_addition_request_categories WHERE request_id=$1 ORDER BY category_id
`

// Fetch relationships only after LockWorkflowRequest completes. A subquery in
// the locking SELECT can retain the pre-wait statement snapshot.
func (q *Queries) WorkflowRequestCategoryIDs(ctx context.Context, requestID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, workflowRequestCategoryIDs, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var category_id pgtype.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
